### ISSUE TITLE
Cannot update Tour Step Name

### ISSUE THREAD

**Issue by melohagan** [JayP718/tour_step_bb_plugin#1]
**Reproduction steps**

1. Add a New Tour Step
2. Try to change the Name
3. See error

![Screenshot 2022-12-06 at 14 50 38](https://user-images.githubusercontent.com/101575380/205944351-0420dbce-5898-4e2d-bcfa-c3fb5e41ccb3.png)

![Screenshot 2022-12-06 at 14 50 51](https://user-images.githubusercontent.com/101575380/205944402-ad2d2aca-1dfb-4f42-896f-c2b5e66ed70d.png)

*Name does not update*
![Screenshot 2022-12-06 at 14 51 21](https://user-images.githubusercontent.com/101575380/205944552-e1f972c2-b191-4b1e-9665-0d3db72a43ae.png)

**Comment by JayP718** [comment]
Hey @melohagan 

That's weird, it's working on cloud and self hosted for me.

Are you on cloud or self hosted? Look at me flipping the script :)

My initial suspicions is that's conflicting with another imported plugin but just an suspicion for now.

JP

**Comment by melohagan** [comment]
Hey @JayP718 

It's working fine for me now on self-hosted. I had been using `develop` branch so it might become an issue in the next release, or it's simply a weird conflict with another plugin as you said.

Closing for now anyway!
